### ISSUE TITLE
About dataset production and baseline

### ISSUE THREAD

**Issue by suetme** [luost26/score-denoise#15]
Thank you for your excellent work!

1. I want to create my own dataset. I wonder if I just need to provide a clean point cloud? I found that this model seems to include a function that adds noise to the point cloud.

2. For some baselines in the article, such as MRPCA and GLR, I found that there seems to be no publicly available code for these methods. Did you implement them yourself?

**Comment by luost26** [comment]
Hi,
Thank you for your interest in our project.

1. Yes, only clean point clouds are needed.
2. We contacted the authors to get the code.
