### ISSUE TITLE
Results on a large number of points

### ISSUE THREAD

**Issue by Siziff** [luost26/score-denoise#18]
Hello:) I launched your model on a large number of points (200 thousand +-) on an airplane model, but there were no improvements to the model. On the left, the point cloud before the change, on the right after the change. I also tried to reduce the number of points to 70 thousand and there was no result either.
1. Why does the model not give results on a large number of points?
2. Does it make sense to try to train the model on your loyal data?
![image](https://user-images.githubusercontent.com/42972554/204732575-030a34aa-f924-48c0-8d20-6fa82e15b61e.png)
![image](https://user-images.githubusercontent.com/42972554/204732878-0513db88-9f47-421b-8aee-34ea7405fff1.png)

**Comment by luost26** [comment]
Hi,

The noisy points are corrected as highlighted in the red box:

<img width="637" alt="image" src="https://user-images.githubusercontent.com/45375360/204775992-7b3af41b-037f-42ec-ad31-6d100225f593.png">

<img width="626" alt="image" src="https://user-images.githubusercontent.com/45375360/204776372-15d33512-3202-4934-8af3-25e78c680031.png">

Other noisy points not denoised by the model are considered outliers (far from the surface and isolated). Our model is not designed to remove outliers. Removing outlying points is easy using statistical methods and Meshlab includes such tools.

**Comment by Siziff** [comment]
Thank you :) and one more question-
Is it important to have the same number of points in each instance of the training sample? or is it possible with a different number of points? For example, is it possible to take instances with 30,000 +- 300 points in the training sample?

**Comment by luost26** [comment]
Different numbers of points are possible.
