### ISSUE TITLE
AttributeError: module 'distutils' has no attribute 'version' 

### ISSUE THREAD

**Issue by olagt** [luost26/score-denoise#19]
Hi 
Thank you for sharing the code.
However, when I invoke command `python test.py --dataset PUNet --resolution 50000_poisson --noise 0.01 --niters 1`

I got AttributeError :
`(score-denoise) ola@ola-ASUS-AI:/media/ola/Int2TB/score-denoise$ python test.py --dataset PUNet --resolution 50000_poisson --noise 0.01 --niters 1

Traceback (most recent call last):
  File "test.py", line 5, in <module>
    import torch.utils.tensorboard
  File "/home/ola/anaconda3/envs/score-denoise/lib/python3.8/site-packages/torch/utils/tensorboard/__init__.py", line 4, in <module>
    LooseVersion = distutils.version.LooseVersion
AttributeError: module 'distutils' has no attribute 'version'

(score-denoise) ola@ola-ASUS-AI:/media/ola/Int2TB/score-denoise$ 
`

I tried to resolve it by 
`conda install setuptools=59.5.0`
and 
`conda install fairseq` 
but without success :( 
I installed by 
`conda env create -f env.yml
conda activate score-denoise`

 python test_single.py and python test_large.py work fine ! 

Any ideas what I can do, please  ?

**Comment by luost26** [comment]
Hi,

It seems that this is a pytorch internal issue depending on the version. Could you try to make your own environment and use the latest version of pytorch?

FYI, in addition to pytorch, the following packages are needed:
- point_cloud_utils: https://github.com/fwilliams/point-cloud-utils
- pytorch3d: https://github.com/facebookresearch/pytorch3d
- pytorch-cluster: https://github.com/rusty1s/pytorch_cluster
- tqdm
- scikit-learn
- pyyaml
- easydict
- tensorboard

**Comment by olagt** [comment]
Thank you , I will try to install the latest version of pytorch and packages you mentioned 

In meantime I noticed when commented out line 5 in test.py `#import torch.utils.tensorboard `
everything seems to work correctly .

Ola
